spring:
  mail:
    host: smtp.163.com
    username: 13940140973@163.com
    password: HMIHMXRUKCUGYUWE
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtualHost: /
  security:
    jwt:
      key: abcdefhijk
      expire: 7
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test

